# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RabbitUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100, unique=True, verbose_name='name')),
                ('mobile', models.BigIntegerField(null=True, verbose_name='mobile')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('login_id', models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='login_id')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rabbituser',
                'verbose_name': 'Rabbit User',
                'verbose_name_plural': 'Rabbit Users',
            },
        ),
        migrations.CreateModel(
            name='HotelUser',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(default=None, max_length=100, unique=True, verbose_name='hotel_name')),
                ('contact_person', models.CharField(default=None, max_length=50, null=True, verbose_name='contact_person')),
                ('contact_number', models.BigIntegerField(null=True, verbose_name='contact_number')),
                ('contact_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='contact_email')),
                ('hotel_address_line_1', models.CharField(default=None, max_length=500, null=True, verbose_name='hotel_address_line_1')),
                ('hotel_address_line_2', models.CharField(default=None, max_length=500, null=True, verbose_name='hotel_address_line_2')),
                ('hotel_address_line_3', models.CharField(default=None, max_length=500, null=True, verbose_name='hotel_address_line_3')),
                ('distance_from_smerkato', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'hoteluser',
                'verbose_name': 'Application User',
                'verbose_name_plural': 'Application Users',
            },
        ),
    ]
